name: c++ CI
on:
    push:
        branches:
        - "**"
    pull_request:
        branches:
        - main
        - develop
jobs:
    check_format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Check format
              run: |
                find -name '*.cpp' -print0 | xargs -0 clang-format --Werror --dry-run
    build-clang:
        needs: check_format
        runs-on: ubuntu-latest
        env: 
            TAG: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/develop' && 'dev') || 'testing' }}
        steps:
            - name: Checkout_code
              uses: actions/checkout@v2
            - name: Build image
              run: | 
                echo "pkutyl/clang_cpp:$TAG"
                docker pull pkutyl/clang_cpp:$TAG
                docker build -f dockerfiles/clang.Dockerfile -t pkutyl/clang_cpp:$TAG .
            - name: Run Container
              run: |
                    docker run -d -it --name clang_cpp pkutyl/clang_cpp:$TAG
                
