name: c++ CI
on:
    push:
        branches:
        - "**"
    pull_request:
        branches:
        - main
        - develop
jobs:
    check_format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Check format
              run: |
                find -name '*.cpp' -print0 | xargs -0 clang-format --Werror --dry-run
