name: c++ CI
on:
    push:
        branches:
        - "**"
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up MSVC 2022
              uses: microsoft/vssetup-action@v1
              with:
                  vswhere-version: 2.x
                  vs-version: 17.0
            - name: Build
              run: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .