name: c++ CI
on:
    push:
        branches:
        - "**"
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up MSVC
              uses: ilammy/msvc-dev-cmd@v1
            - name: Build
              run: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .
                    dir
                    cd tests
                    dir
                    cd exec.dir