name: c++ CI WINDOWS
on:
    push:
        branches:
        - "**"
    pull_request:
        branches: [develop, main]
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up MSVC
              uses: ilammy/msvc-dev-cmd@v1
            - name: Build
              run: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .
                    cd tests/Debug
                    ./exec.exe