name: C++ CD Server deployment
on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        branch:
            description: 'Branch to deploy (main or develop)'
            required: true
            type: choice
            options:
            - main
            - develop
            default: 'develop'

jobs:
    deploy_app:
        runs-on: ubuntu-latest
        if: ${{github.event.inputs.branch == 'develop' || github.event.inputs.branch == 'main' }}
        env:
            DIR: ${{ (github.ref == 'refs/heads/main' && 'app_production') || (github.ref == 'refs/heads/develop' && 'app_develop') || 'app_test' }}
        steps:
            - name: install ssh keys
              run: |
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
            - name: cleanup
              run: rm -rf ~/.ssh
